//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunderassenverwaltung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurrsSet
    {
        public FurrsSet()
        {
            this.RacesSet = new HashSet<RacesSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RacesSet> RacesSet { get; set; }
    }
}
