//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunderassenverwaltung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RacesSet
    {
        public RacesSet()
        {
            this.CharacteristicsSet = new HashSet<CharacteristicsSet>();
            this.SocialUsagesSet = new HashSet<SocialUsagesSet>();
            this.WorkUsagesSet = new HashSet<WorkUsagesSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short MinimumAge { get; set; }
        public short MaximumAge { get; set; }
        public short MinimumWeight { get; set; }
        public short MaximumWeight { get; set; }
        public short MinimumWithers { get; set; }
        public string MaximumWithers { get; set; }
        public string History { get; set; }
        public string GeneralInformation { get; set; }
        public string PayAttentionTo { get; set; }
        public byte[] Picture { get; set; }
        public int Furrs_Id { get; set; }
        public int Groups_Id { get; set; }
        public string Country { get; set; }
    
        public virtual FurrsSet FurrsSet { get; set; }
        public virtual GroupsSet GroupsSet { get; set; }
        public virtual ICollection<CharacteristicsSet> CharacteristicsSet { get; set; }
        public virtual ICollection<SocialUsagesSet> SocialUsagesSet { get; set; }
        public virtual ICollection<WorkUsagesSet> WorkUsagesSet { get; set; }
    }
}
